__version__ = "0.0.1"

from icd_override.custom.report.gate_out_pass.custom_gate_out_pass import execute as custom_gate_out_pass_execute
import icd_tz.icd_tz.report.gate_out_pass.gate_out_pass
from icd_override.custom.report.exited_containers.custom_exited_containers import execute as custom_exited_containers_execute
import icd_tz.icd_tz.report.exited_containers.exited_containers
from icd_override.custom.report.current_container_stock.custom_current_container_stock import execute as custom_current_container_stock_execute
import icd_tz.icd_tz.report.current_container_stock.current_container_stock

from icd_override.custom.custom_sales_order import get_storage_services as custom_sales_order_get_storage_services
import icd_tz.icd_tz.api.sales_order

from icd_override.custom.custom_sales_invoice import update_sales_references as custom_sales_invoice_update_sales_references
import icd_tz.icd_tz.api.sales_invoice

from icd_override.custom.custom_gate_pass import auto_expire_gate_passes as custom_auto_expire_gate_passes
import icd_tz.icd_tz.doctype.gate_pass.gate_pass

icd_tz.icd_tz.report.gate_out_pass.gate_out_pass.execute = custom_gate_out_pass_execute
icd_tz.icd_tz.report.exited_containers.exited_containers.execute = custom_exited_containers_execute
icd_tz.icd_tz.report.current_container_stock.current_container_stock.execute = custom_current_container_stock_execute

icd_tz.icd_tz.api.sales_order.get_storage_services = custom_sales_order_get_storage_services
icd_tz.icd_tz.api.sales_invoice.update_sales_references = custom_sales_invoice_update_sales_references
icd_tz.icd_tz.doctype.gate_pass.gate_pass.auto_expire_gate_passes = custom_auto_expire_gate_passes